services:
  cs2-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cs2-server

    # Ressourcen-Limits direkt in der Compose (Single Source of Truth)
    deploy:
      resources:
        limits:
          cpus: '3.5'
          memory: 20G
    
    # Port-Mapping laut Guide (Outside of Proxy control)
    ports:
      - "27015:27015/udp"
      - "27015:27015/tcp"
      - "27020:27020/udp"
      - "26900:26900/udp"
      - "27005:27005/udp"

    restart: unless-stopped
    ulimits:
      nice:
        soft: -20
        hard: -20
        
    environment:
      - STEAM_GAMESERVER_API=${STEAM_TOKEN:?}
      - EXTRA_PARAMS=${EXTRA_PARAMS}
      - ALWAYS_UPDATE_ON_START=${ALWAYS_UPDATE_ON_START:-true}
      - INSTALL_MODDING=${INSTALL_MODDING:-false}
      - DOTNET_EnableWriteXorExecute=1
      - CPU_CORE_COUNT=${CPU_CORE_COUNT:?3}
      - TZ=Europe/Berlin
      
    volumes:
      # Formatierung nach deinem Guide (is_directory: true)
      - type: bind
        source: ./cs2-data
        target: /cs2-data
        is_directory: true
      - type: bind
        source: ./fex-data
        target: /home/steam/.fex-emu
        is_directory: true
      
    stdin_open: true
    tty: true
    entrypoint: /home/steam/init-server.sh
