services:
  cs2-server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: cs2-server

    # Ressourcen-Limits direkt in der Compose (Single Source of Truth)
    deploy:
      resources:
        limits:
          cpus: '3.5'
          memory: 20G
    # Uses host networking for lower latency (without docker-proxy)
    network_mode: host

    restart: unless-stopped
    ulimits:
      nice:
        soft: -20
        hard: -20
        
    environment:
      - STEAM_GAMESERVER_API=${STEAM_TOKEN:?}
      - EXTRA_PARAMS=${EXTRA_PARAMS}
      - ALWAYS_UPDATE_ON_START=${ALWAYS_UPDATE_ON_START:-true}
      - INSTALL_MODDING=${INSTALL_MODDING:-false}
      - DOTNET_EnableWriteXorExecute=1
      - CPU_CORE_COUNT=${CPU_CORE_COUNT:?3}
      - TZ=Europe/Berlin
      
    volumes:
      - cs2-data:/cs2-data
      - fex-data:/home/steam/.fex-emu
      
    stdin_open: true
    tty: true
    entrypoint: /home/steam/init-server.sh

volumes:
  cs2-data:
  fex-data:
