services:
  cs2-server:
    image: 'cs2-arm64'
    container_name: 'cs2-server'
    ports:
      - '27015:27015/udp'
      - '27015:27015/tcp'
      # add more ports if u want
    restart: 'unless-stopped'
    ulimits:
      nice:
        soft: -20
        hard: -20
    environment:
      - STEAM_GAMESERVER_API=${STEAM_GAMESERVER_API:-}
      - STARTUP_MAP=${STARTUP_MAP:-de_dust2}

      - CPU_CORE_COUNT=${CPU_CORE_COUNT:-3}
      - PUID=${PUID:-1000}
      - PGID=${PGID:-1000}

      - ALWAYS_UPDATE_ON_START=${ALWAYS_UPDATE_ON_START:-true}
      - INSTALL_MODDING=${INSTALL_MODDING:-false}
      - DOTNET_EnableWriteXorExecute=1

      - EXTRA_PARAMS=>
        +mat_queue_mode 2
        -nojoy
        -nohltv
        +engine_no_focus_sleep 0
        +fps_max 64
        +sv_max_usercmd_future_ticks 8
        +sv_hibernate_when_empty 0
    volumes:
      - './cs2-data:/cs2-data'
      - './init-server.sh:/home/steam/init-server.sh:rw'
      - './fex-data:/home/steam/.fex-emu'
    stdin_open: true
    tty: true
    entrypoint: /home/steam/init-server.sh
