name: CS2 ARM64 CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  shellcheck:
    name: Lint bash scripts
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Run ShellCheck
        uses: ludeeus/action-shellcheck@master
        with:
          scandir: './'


  build-test:
    name: Build docker images
    runs-on: ubuntu-22.04-arm
    needs: shellcheck
    steps:
      - name: Checkout code
        uses: actions/checkout@v6

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v4

      - name: Test build (Generic)
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile.generic
          platforms: linux/arm64
          push: false
          tags: cs2-arm64:generic-ci

      - name: Test build (Oracle Ampere)
        uses: docker/build-push-action@v7
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/arm64
          push: false
          tags: cs2-arm64:ampere-ci